### ISSUE TITLE
Error when using sass bud extenion

### ISSUE THREAD

**Issue by 970DesignUser** [roots/bud#1242]
I'm attempting to use the bud extension for sass, but using any build after it is installed throws an error - Error: TypeError: app.hooks.on(...).build.setLoader is not a function

This is the full error output:

```
% yarn build
yarn run v1.22.10
warning ../../../../../../package.json: No license field
$ bud build
[root] › ✖  Error: TypeError: app.hooks.on(...).build.setLoader is not a function 
    at Extensions.registerExtension ([secure]/node_modules/@roots/bud-extensions/lib/cjs/Extensions/extensions.service.js:134:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async [secure]/node_modules/@roots/bud-extensions/lib/cjs/Extensions/extensions.service.js:99:17
    at async [secure]/node_modules/@roots/bud-extensions/lib/cjs/Extensions/extensions.service.js:98:17
    at async [secure]/node_modules/@roots/bud-extensions/lib/cjs/Extensions/extensions.service.js:98:17
    at async [secure]/node_modules/@roots/bud-extensions/lib/cjs/Extensions/extensions.service.js:98:17
    at async [secure]/node_modules/@roots/bud-extensions/lib/cjs/Extensions/extensions.service.js:98:17
    at async [secure]/node_modules/@roots/bud-extensions/lib/cjs/Extensions/extensions.service.js:98:17
    at async [secure]/node_modules/@roots/bud-extensions/lib/cjs/Extensions/extensions.service.js:98:17
    at async [secure]/node_modules/@roots/bud-extensions/lib/cjs/Extensions/extensions.service.js:98:17
Internal Error: Error: TypeError: app.hooks.on(...).build.setLoader is not a function
    at Bud.error (/Users/tjszewczak/Sites/locale/web/app/themes/locale/node_modules/@roots/bud-framework/lib/cjs/Framework/index.js:544:15)
    at Extensions.injectExtensions (/Users/tjszewczak/Sites/locale/web/app/themes/locale/node_modules/@roots/bud-extensions/lib/cjs/Extensions/extensions.service.js:107:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Extensions.boot (/Users/tjszewczak/Sites/locale/web/app/themes/locale/node_modules/@roots/bud-extensions/lib/cjs/Extensions/extensions.service.js:73:9)
    at async /Users/tjszewczak/Sites/locale/web/app/themes/locale/node_modules/@roots/bud-framework/lib/cjs/Framework/lifecycle/index.js:56:13
    at async Promise.all (index 3)
    at async /Users/tjszewczak/Sites/locale/web/app/themes/locale/node_modules/@roots/bud-framework/lib/cjs/Framework/lifecycle/index.js:51:9
    at async /Users/tjszewczak/Sites/locale/web/app/themes/locale/node_modules/@roots/bud-framework/lib/cjs/Framework/lifecycle/index.js:47:9
    at async Bud.lifecycle (/Users/tjszewczak/Sites/locale/web/app/themes/locale/node_modules/@roots/bud-framework/lib/cjs/Framework/lifecycle/index.js:46:5)
    at async factory (/Users/tjszewczak/Sites/locale/web/app/themes/locale/node_modules/@roots/bud/lib/cjs/factory/index.js:55:5)
[root] › ❯  registering action: event.project.write 1 registered
[root] › ✔  [2/4] boot cache
[process] › ℹ  info      beforeExit
[process] › ℹ  info      exit
✨  Done in 2.31s.
```

Here's my package.json:

```
{
  "name": "sage",
  "private": true,
  "browserslist": [
    "extends @wordpress/browserslist-config"
  ],
  "engines": {
    "node": ">=16.0.0"
  },
  "scripts": {
    "dev": "bud dev",
    "build": "bud build",
    "translate": "npm run translate:pot && npm run translate:js",
    "translate:pot": "wp i18n make-pot . ./resources/lang/sage.pot --ignore-domain --include=\"app,resources\"",
    "translate:js": "wp i18n make-json ./resources/lang --pretty-print"
  },
  "devDependencies": {
    "@roots/bud": "5.5.0",
    "@roots/bud-postcss": "^5.6.2",
    "@roots/bud-sass": "^5.6.2",
    "@roots/sage": "5.5.0"
  }
}
```

Everything builds as expected when sass/postcss extensions are omitted & uninstalled.  I'm using node v16.3.0 (with npm 6.14.13).

**Comment by kellymears** [comment]
You need to bump `@roots/bud` and `@roots/sage` to 5.6.2.

**Comment by 970DesignUser** [comment]
Thanks - that was it!
