### ISSUE TITLE
[bug] bud-sass loader not registering, ignores files using a transpiler source

### ISSUE THREAD

**Issue by responsemktg** [roots/bud#1728]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

I have a need to load styles/js from other directories than `./resources`. I wish to compile .scss files in a directory to their own CSS files. 

I have created a test directory in the root of my sage theme, containing an empty `script.js` and an empty `style.scss`

I then add the test folder to the entry point:
```js
  app
    /**
     * Application entrypoints
     */
     .entry({
      app: ["@scripts/app", "@styles/app"],
      editor: ["@scripts/editor", "@styles/editor"],
      test: [app.path("./test/script.js"), app.path("./test/style.scss")]
    })
```
After that, I add a transpiler source to the js and sass rules:
```js
  app.build.rules.js.setInclude([
    bud => bud.path('@src'),
    bud => bud.path('./test'),
  ])
```

This works fine, but the .scss file is ignored. So I go ahead and try add another source to the sass rule:
```js
  app.build.rules.sass.setInclude([
    bud => bud.path('@src'),
    bud => bud.path('./test'),
  ])
```

Which throws an error:
` Type Error: Cannot read properties of undefined (reading 'setInclude') `

In my bud config, I console log out the `app.build.rules` and see there is no sass rule:
```js
{
  yml: Rule {
    _app: [Function (anonymous)],
    include: [ [Function (anonymous)] ],
    test: [Function (anonymous)],
    use: [ 'yml' ]
  },
  webp: Rule {
    _app: [Function (anonymous)],
    test: [Function (anonymous)],
    include: [ [Function (anonymous)] ],
    type: 'asset/resource',
    generator: [Function (anonymous)]
  },
  svg: Rule {
    _app: [Function (anonymous)],
    test: [Function (anonymous)],
    include: [ [Function (anonymous)] ],
    type: 'asset/resource',
    generator: [Function: bound svgGenerator]
  },
  json: Rule {
    _app: [Function (anonymous)],
    type: 'json',
    include: [ [Function (anonymous)] ],
    test: [Function (anonymous)],
    parser: [Function (anonymous)]
  },
  js: Rule {
    _app: [Function (anonymous)],
    test: [Function (anonymous)],
    include: [ [Function (anonymous)] ],
    use: [ [Item] ]
  },
  image: Rule {
    _app: [Function (anonymous)],
    test: [Function (anonymous)],
    include: [ [Function (anonymous)] ],
    type: 'asset/resource',
    generator: [Function (anonymous)]
  },
  html: Rule {
    _app: [Function (anonymous)],
    include: [ [Function (anonymous)] ],
    test: [Function (anonymous)],
    use: [ 'html' ]
  },
  font: Rule {
    _app: [Function (anonymous)],
    type: 'asset',
    test: [Function (anonymous)],
    include: [ [Function (anonymous)] ],
    generator: [Function (anonymous)]
  },
  cssModule: Rule {
    _app: [Function (anonymous)],
    test: [Function (anonymous)],
    include: [ [Function (anonymous)] ],
    use: [ 'precss', 'cssModule', 'postcss' ]
  },
  css: Rule {
    _app: [Function (anonymous)],
    test: [Function (anonymous)],
    include: [ [Function (anonymous)] ],
    use: [ 'precss', 'css', 'postcss' ]
  }
}
```

### Expected Behavior

.scss files in additional entry points, that have a transpiler source - to be parsed using bud-sass 

### Actual Behavior

This error is thrown: `Type Error: Cannot read properties of undefined (reading 'setInclude')`

### Steps To Reproduce

1. Create a test folder in the root of the teme
2. Add a blank script.js and style.scss to the folder
3. Add the entry points for the test folder into the bud config
4. Add transpiler sources for the js/sass rules

### version

6.4.4

### What package manager are you using?

npm

### version

8.15.0

### Logs

```zsh
Type Error: Cannot read properties of undefined (reading 'setInclude')
    at default (file:///Users/marcbroad/Desktop/www/sallys/site/web/app/themes/sage/bud.config.mjs:19:24)
    at Configuration.run (file:///Users/marcbroad/Desktop/www/sallys/site/web/app/themes/sage/node_modules/@roots/bud-framework/lib/configuration/configuration.js:30:26)
    at file:///Users/marcbroad/Desktop/www/sallys/site/web/app/themes/sage/node_modules/@roots/bud-framework/lib/configuration/index.js:14:29
    at Array.map (<anonymous>)
    at Module.process (file:///Users/marcbroad/Desktop/www/sallys/site/web/app/themes/sage/node_modules/@roots/bud-framework/lib/configuration/index.js:13:60)
    at Bud.run (file:///Users/marcbroad/Desktop/www/sallys/site/web/app/themes/sage/node_modules/@roots/bud-framework/lib/methods/run.js:5:29)
    at BuildDevelopmentCommand.runCommand (file:///Users/marcbroad/Desktop/www/sallys/site/web/app/themes/sage/node_modules/@roots/bud/lib/cli/commands/build.base.js:192:24)
    at BuildDevelopmentCommand.execute (file:///Users/marcbroad/Desktop/www/sallys/site/web/app/themes/sage/node_modules/@roots/bud/lib/cli/commands/base.js:179:24)
    at async BuildDevelopmentCommand.validateAndExecute (/Users/marcbroad/Desktop/www/sallys/site/web/app/themes/sage/node_modules/clipanion/lib/advanced/Command.js:73:26)
    at async Cli.run (/Users/marcbroad/Desktop/www/sallys/site/web/app/themes/sage/node_modules/clipanion/lib/advanced/Cli.js:222:24)
```

### Configuration

```zsh
// @ts-check

/**
 * Build configuration
 *
 * @see {@link https://bud.js.org/guides/configure}
 * @param {import('@roots/bud').Bud} app
 */
export default async (app) => {

  console.log(app.build.rules)


  app.build.rules.js.setInclude([
    bud => bud.path('@src'),
    bud => bud.path('./test'),
  ])

  app.build.rules.scss.setInclude([
    bud => bud.path('@src'),
    bud => bud.path('./test'),
  ])

  app
    /**
     * Application entrypoints
     */
     .entry({
      app: ["@scripts/app", "@styles/app"],
      editor: ["@scripts/editor", "@styles/editor"],
      test: [app.path("./test/script.js"), app.path("./test/style.scss")]
    })

    /**
     * Directory contents to be included in the compilation
     */
    .assets(["images"])

    /**
     * Matched files trigger a page reload when modified
     */
    .watch(["resources/views/**/*", "app/**/*"])

    /**
     * Proxy origin (`WP_HOME`)
     */
    .proxy("http://example.test")

    /**
     * Development origin
     */
    .serve("http://0.0.0.0:3000")

    /**
     * URI of the `public` directory
     */
    .setPublicPath("/app/themes/sage/public/")

    /**
     * Generate WordPress `theme.json`
     *
     * @note This overwrites `theme.json` on every build.
     */
    .wpjson
      .settings({
        color: {
          custom: false,
          customGradient: false,
          defaultPalette: false,
          defaultGradients: false,
        },
        custom: {
          spacing: {},
          typography: {
            'font-size': {},
            'line-height': {},
          },
        },
        spacing: {
          padding: true,
          units: ['px', '%', 'em', 'rem', 'vw', 'vh'],
        },
        typography: {
          customFontSize: false,
        },
      })
      .useTailwindColors()
      .useTailwindFontFamily()
      .useTailwindFontSize()
      .enable()
};
```

**Comment by kellymears** [comment]
Hey, thanks for the issue. This is a documentation issue.

The docs should recommend using `bud.build` methods within a `config.after` hook. The loader is not registered early enough for your configuration.

```ts
app.hooks.action(`config.after`, async (app) => {
  app.build.rules.sass.setInclude([
    app => app.path('@src'),
    app => app.path('./test'),
  ])
})
```

**Comment by responsemktg** [comment]
> Hey, thanks for the issue. This is a documentation issue.
> 
> The docs should recommend using `bud.build` methods within a `config.after` hook. The loader is not registered early enough for your configuration.
> 
> ```ts
> app.hooks.action(`config.after`, async (app) => {
>   app.build.rules.sass.setInclude([
>     app => app.path('@src'),
>     app => app.path('./test'),
>   ])
> })
> ```

@kellymears  Awesome, that definitely helps that issue!
There is another issue now (let me know if you want this in a separate post) where the hot reload now doesn't work with changes to the app.css - _**but does work**_ with changes to the test/style.scss.
Periodically this message comes up in the console:

```js
test.js:1567 Uncaught TypeError: Cannot set properties of undefined (setting './node_modules/css-loader/dist/cjs.js??css!./node_modules/postcss-loader/dist/cjs.js??postcss!./resources/styles/app.css')
    at self.webpackHotUpdatesage (test.js:1567:39)
    at app.1764c00a1e8f430d84d2.hot-update.js:10:29
```

<img width="731" alt="Screen Shot 2022-09-29 at 2 49 53 PM" src="https://user-images.githubusercontent.com/15894740/193117442-decbc39f-d6f9-4046-8b8d-b4bdd0a521e9.png">

Im not sure if that's a known issue at this point, but I couldn't find anything referencing that issue specifically.

**Comment by kellymears** [comment]
> (let me know if you want this in a separate post)

👍🏽

@responsemktg let's track this second issue separately. I don't think it's related.

I'm keeping this open until the docs are updated

**Comment by kellymears** [comment]
this docs update is deployed
