### ISSUE TITLE
[bug] Error when trying to build the project !

### ISSUE THREAD

**Issue by MustafaFahmy-FE** [roots/bud#2288]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

I have a wordpress project that built using Docker, Sage theme and Bud

When trying to build the project using
`npm run build` or `npx run build`

I got this error
`
> build
> bud build

node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at readFile (node:fs:402:10)
    at go$readFile (H:\GitHub\Alf-healthcare\wp-content\themes\sage\node_modules\@roots\bud-support\lib\cjs\index.js:28440:14)
    at readFile (H:\GitHub\Alf-healthcare\wp-content\themes\sage\node_modules\@roots\bud-support\lib\cjs\index.js:28437:12)
    at H:\GitHub\Alf-healthcare\wp-content\themes\sage\node_modules\@roots\bud-support\lib\cjs\index.js:131529:12
    at new Promise (<anonymous>)
    at readFile (H:\GitHub\Alf-healthcare\wp-content\themes\sage\node_modules\@roots\bud-support\lib\cjs\index.js:131528:14)
    at Object._readFile (H:\GitHub\Alf-healthcare\wp-content\themes\sage\node_modules\@roots\bud-support\lib\cjs\index.js:84367:58)
    at Object._readFile (H:\GitHub\Alf-healthcare\wp-content\themes\sage\node_modules\@roots\bud-support\lib\cjs\index.js:131542:45)
    at Manifest.read (H:\GitHub\Alf-healthcare\wp-content\themes\sage\node_modules\@roots\bud\lib\cjs\context\manifest.js:10:39)
    at makeContext (H:\GitHub\Alf-healthcare\wp-content\themes\sage\node_modules\@roots\bud\lib\cjs\context\index.js:31:58) {
  code: 'ERR_INVALID_ARG_TYPE'
}`

I tried several solutions but with no result still the same error every time I build the project

Node v 16
Windows 10

### version

5.8.7

**Comment by retlehs** [comment]
WSL is a requirement to use bud.js on Windows. Please use Roots Discourse for support requests.
