### ISSUE TITLE
[bug] could not import sass: problem running hook booted

### ISSUE THREAD

**Issue by mheiduk** [roots/bud#2311]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

On a new sage install with bud and bud-sass installed, after running `yarn build` I am not able to build app.scss/editor.scss. On already existing projects, it works fine though. When copying the node_modules dir from projects, where the build goes through, to the newly created project, everything works as expected.

### Expected Behavior

Building assets

### Actual Behavior

Not building assets

### Steps To Reproduce

1. install clean sage with bud
2. add bud-sass
3. rename app.css/editor.css to app.scss/editor.scss
4. run `yarn build`

### version

6.12.3

### Logs

```zsh
yarn run v1.22.19
$ bud build --log
[env] › ▶  sourcing .env values Initialized timer...
[env] › registering values /Users/xxx/xxx/xxx/.env
[env] › registering expanded values /Users/xxx/xxx/xxx/.env
[env] › ◼  sourcing .env values Timer run for: 2ms
[fs] › ▶  Initializing filesystem Initialized timer...
[fs] › …  removing old module resolutions
[fs] › ✔  removing old module resolutions
[fs] › ◼  Initializing filesystem Timer run for: 6ms
[bootstrap] › 🏗️ building sage
[bootstrap] › 📂 basedir /Users/xxx/xxx/xxx/web/app/themes/xxx
[bootstrap] › 😎 version 6.12.3
[sage] › ▶  initialize Initialized timer...
[sage] › bud.env ← @roots/bud/services/env
[sage] › bud.consoleBuffer ← @roots/bud-framework/services/console
[sage] › bud.project ← @roots/bud/services/project
[sage] › bud.cache ← @roots/bud-cache
[sage] › bud.compiler ← @roots/bud-compiler
[sage] › bud.extensions ← @roots/bud-extensions
[sage] › bud.hooks ← @roots/bud-hooks
[sage] › bud.dashboard ← @roots/bud-dashboard
[sage] › bud.build ← @roots/bud-build
[sage] › bud.notifier ← @roots/bud-framework/services/notifier
[sage] › bud.api ← @roots/bud-api
[sage] [hooks] › ▶  bootstrap Initialized timer...
[sage] [hooks] › …  executing callback 1/2
[sage] [hooks] › …  executing callback 2/2
[sage] [hooks] › ✔  executing callback 1/2
[sage] [hooks] › ✔  executing callback 2/2
[sage] [hooks] › ◼  bootstrap Timer run for: 0ms
[sage] [hooks] › ▶  register  Initialized timer...
[sage] [hooks] › …  executing callback 1/3
[sage] [hooks] › …  executing callback 2/3
[sage] [hooks] › …  executing callback 3/3
[sage] [hooks] › ✔  executing callback 1/3
[sage] [hooks] › ✔  executing callback 2/3
[sage] [hooks] › ✔  executing callback 3/3
[sage] [hooks] › ◼  register  Timer run for: 4ms
[sage] [hooks] › ▶  boot      Initialized timer...
[sage] [hooks] › …  executing callback 1/1
[sage] [hooks] › ✔  executing callback 1/1
[sage] [hooks] › ◼  boot      Timer run for: 17ms
[sage] [hooks] › ▶  booted    Initialized timer...
[sage] [hooks] › …  executing callback 1/2
[sage] [hooks] › …  executing callback 2/2
[sage] [extensions] › ✔  set @roots/bud-cache/invalidate-cache
[sage] [@roots/bud-cache/invalidate-cache] › ✔  registered
[sage] [cache] › ✔  cache initialized
[sage] [hooks] › ✔  executing callback 1/2
[sage] [extensions] › ✔  set @roots/bud-extensions/esm
[sage] [extensions] › ✔  set @roots/bud-extensions/cdn
[sage] [extensions] › ✔  set @roots/bud-extensions/html-webpack-plugin
[sage] [extensions] › ✔  set @roots/bud-extensions/interpolate-html-webpack-plugin
[sage] [extensions] › ✔  set @roots/bud-extensions/mini-css-extract-plugin
[sage] [extensions] › ✔  set @roots/bud-extensions/webpack-define-plugin
[sage] [extensions] › ✔  set @roots/bud-extensions/webpack-hot-module-replacement-plugin
[sage] [extensions] › ✔  set @roots/bud-extensions/webpack-provide-plugin
[sage] [extensions] › ✔  set @roots/bud-extensions/fix-style-only-entrypoints
[sage] [extensions] › ✔  set @roots/bud-extensions/copy-webpack-plugin
[sage] [extensions] › ✔  set @roots/bud-extensions/webpack-manifest-plugin
[sage] [extensions] › ✔  set @roots/bud-extensions/clean-webpack-plugin
[sage] [extensions] › ✔  set @roots/bud-entrypoints
[sage] [extensions] › ✔  set @roots/bud-terser/css-minimizer
[sage] [extensions] › ✔  set @roots/bud-terser
[sage] [extensions] › ✔  set @roots/bud-sass/resolve-url
[sage] [extensions] › ✔  set @roots/bud-imagemin/sharp
[sage] [extensions] › ✔  set @roots/bud-imagemin/svgo
[sage] [extensions] › ✔  set @roots/bud-imagemin
[sage] [extensions] › ✔  set @roots/bud-postcss
[sage] [extensions] › ✔  set @roots/bud-postcss
[sage] [extensions] › ✔  set @roots/bud-purgecss
[sage] [extensions] › ✔  set @roots/bud-sass
[sage] [extensions] › ✔  set @roots/sage/acorn
[sage] [extensions] › ✔  set @roots/sage/blade-loader
[sage] [extensions] › ✔  set @roots/bud-preset-recommend
[sage] [extensions] › ✔  set @roots/bud-wordpress-theme-json
[sage] [extensions] › ✔  set @roots/bud-react/react-refresh
[sage] [extensions] › ✔  set @roots/bud-react
[sage] [extensions] › ✔  set @roots/bud-wordpress-dependencies
[sage] [extensions] › ✔  set @roots/bud-wordpress-externals
[sage] [extensions] › ✔  set @roots/bud-wordpress-manifests
[sage] [extensions] › ✔  set @roots/bud-preset-wordpress
[sage] [extensions] › ✔  set @roots/sage
[sage] [@roots/bud-extensions/webpack-define-plugin] › ✔  registered
[sage] [@roots/bud-sass/resolve-url] › ✔  registered
[sage] [@roots/bud-imagemin/sharp] › ✔  registered
[sage] [@roots/bud-imagemin/svgo] › ✔  registered
[sage] [@roots/bud-imagemin] › ✔  registered
[sage] [@roots/bud-postcss] › ✔  registered
[sage] [@roots/bud-purgecss] › ✔  registered
[sage] › ✖  (node:31506) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)

 ImportError

✘ could not import sass
problem running hook booted

☰ Stack trace
problem running hook booted
    at BudSass.import (node_modules/@roots/bud-framework/lib/extension/index.js:257:19)
    at async BudSass.register (node_modules/@roots/bud-sass/lib/extension.js:12:32)
    at async BudSass._register (node_modules/@roots/bud-framework/lib/extension/index.js:67:13)
```

### Configuration

```zsh
Node v20.2.0
Yarn v1.22.19
Bud v6.12.3
Sage v10.6.0
```

### Relevant .budfiles

```zsh
bud.config.js


/**
 * Compiler configuration
 *
 * @see {@link https://roots.io/docs/sage sage documentation}
 * @see {@link https://bud.js.org/guides/configure bud.js configuration guide}
 *
 * @param {import('@roots/bud').Bud} app
 */
export default async (app) => {
  /**
   * Application assets & entrypoints
   *
   * @see {@link https://bud.js.org/docs/bud.entry}
   * @see {@link https://bud.js.org/docs/bud.assets}
   */
  app
    .entry('app', ['@scripts/app', '@styles/app'])
    .entry('editor', ['@scripts/editor', '@styles/editor'])
    .assets(['images']);

  /**
   * Set public path
   *
   * @see {@link https://bud.js.org/docs/bud.setPublicPath}
   */
  app.setPublicPath('/app/themes/xxx/public/');

  /**
   * Development server settings
   *
   * @see {@link https://bud.js.org/docs/bud.setUrl}
   * @see {@link https://bud.js.org/docs/bud.setProxyUrl}
   * @see {@link https://bud.js.org/docs/bud.watch}
   */
  app
    .setUrl('http://localhost:3000')
    .setProxyUrl('http://xxx.test')
    .watch(['resources/views', 'app']);
};
```

**Comment by retlehs** [comment]
A new Sass version was published yesterday which is causing this issue:

https://github.com/sass/dart-sass/issues/1995

Looks like they'll have it resolved sometime today

You can get up and running by installing the previous version: `yarn add sass@1.62.1 --dev`

**Comment by skimsafe-weblate** [comment]
we dont have all day, so thank god for the fix you provided @retlehs

**Comment by kellymears** [comment]
I fully locked sass for 6.13.0.

[sources/@roots/bud-sass/package.json](https://github.com/roots/bud/pull/2309/files#diff-3389a0feb2f366f11edaae181afaa1cf86c413117871d77ef2c5a056cd3361b5R110-R119)

**Comment by kellymears** [comment]
I'm closing this issue. The current version of sass shipping with bud is locked to 1.63.6.
