### ISSUE TITLE
[bug] v6.19.0: `Could not import @roots/bud-framework/env`

### ISSUE THREAD

**Issue by retlehs** [roots/bud#2523]
### Describe the issue

Upgrading to v6.19.0 results in an error when running some bud commands. The build command:

```
BudError

✘ Could not import @roots/bud-framework/env

ℹ Stack trace

│  at Module.import (./node_modules/@roots/bud-framework/lib/module.js:144:28)
│  at async ./node_modules/@roots/bud-framework/lib/bootstrap.js:91:21
│  at async Promise.all (index 0)
│  at async bootstrap (./node_modules/@roots/bud-framework/lib/bootstrap.js:125:5)
│  at async Bud.initialize (./node_modules/@roots/bud-framework/lib/bud/index.js:116:9)
│  at async BudBuildCommand.makeBud (./node_modules/@roots/bud/lib/cli/commands/index.js:216:20)
│  at async BudBuildCommand.execute (./node_modules/@roots/bud/lib/cli/commands/build/index.js:76:9)
│  at async BudBuildCommand.validateAndExecute (./node_modules/clipanion/lib/advanced/Command.js:73:26)
│  at async Cli.run (./node_modules/clipanion/lib/advanced/Cli.js:229:24)

error Command failed with exit code 1.
```

Project: Sage 10 on yarn classic with Node v18.16.0

Tried `rm -rf node_modules && yarn cache clean` ❌ 

### version

v6.19.0 

Reported orginally at https://discourse.roots.io/t/bud-6-19-error-loading-roots-bud-framework-env/26421

**Comment by retlehs** [comment]
You can get around this error for now by forcing the build:

`yarn build --force`
