### ISSUE TITLE
[bug] create-bud-app: Stylelint errors "place-content"

### ISSUE THREAD

**Issue by bnjmnrsh** [roots/bud#2549]
### Agreement

- [X] This is not a duplicate of an existing issue
- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Describe the issue

using `cli` into an empty directory:

`npx create-bud-app --wordpress --customize`

I chose to install babble, sass, eslint, prettier and stylelint. 

It appears the CLI choked with: `✖  Expected shorthand property "place-content" declaration-block-no-redundant-longhand-properties`

### Expected Behavior

Builds without issue

### Actual Behavior

The installed `package.json`:

```
  "devDependencies": {
    "@roots/bud": "^6.20.0",
    "@roots/bud-babel": "^6.20.0",
    "@roots/bud-eslint": "^6.20.0",
    "@roots/bud-postcss": "^6.20.0",
    "@roots/bud-preset-wordpress": "^6.20.0",
    "@roots/bud-prettier": "^6.20.0",
    "@roots/bud-sass": "^6.20.0",
    "@roots/bud-stylelint": "^6.20.0",
    "@roots/bud-swc": "^6.20.0",
    "@roots/eslint-config": "^6.20.0",
    "typescript": "^5.3.3"
  }
```

<details>
<summary>Output of CLI with errors:</summary>

```
Internal Error: Command failed with exit code 1: npx bud build --force --no-cache

Checking for browserslist updates...
  --> This check runs once per week when a browserslist is specified in package.json
  --> You can disable this behavior with the --no-browserslist-update flag or by setting BUD_BROWSERSLIST_UPDATE=false in your project .env file.
  --> ✔ browserslist successfully updated

╭ ran-plugin-starter [98f7c13d0db92d95]                                     ./dist
│
│ │ [stylelint]
│ │ src/index.scss
│ │  19:3  ✖  Expected shorthand property "place-content"
│ │ declaration-block-no-redundant-longhand-properties
│ │ 1 problem (1 error, 0 warnings)
│
╰ 1 error


Checking for browserslist updates...
  --> This check runs once per week when a browserslist is specified in package.json
  --> You can disable this behavior with the --no-browserslist-update flag or by setting BUD_BROWSERSLIST_UPDATE=false in your project .env file.
  --> ✔ browserslist successfully updated

╭ ran-plugin-starter [98f7c13d0db92d95]                                     ./dist
│
│ │ [stylelint]
│ │ src/index.scss
│ │  19:3  ✖  Expected shorthand property "place-content"
│ │ declaration-block-no-redundant-longhand-properties
│ │ 1 problem (1 error, 0 warnings)
│
╰ 1 error

    at makeError (file:///Users/<redacted>/.npm/_npx/<redacted>/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///Users/<redacted>/.npm/_npx/<redacted>/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildTask (file:///Users/<redacted>/.npm/_npx/<redacted>/node_modules/create-bud-app/lib/tasks/build.js:10:17)
    at async CreateCommand.runTasks (file:///Users/<redacted>/.npm/_npx/<redacted>/node_modules/create-bud-app/lib/commands/create.js:504:9)
    at async CreateCommand.execute (file:///Users/<redacted>/.npm/_npx/<redacted>/node_modules/create-bud-app/lib/commands/create.js:414:9)
    at async CreateCommand.validateAndExecute (/Users/<redacted>/.npm/_npx/<redacted>/node_modules/clipanion/lib/advanced/Command.js:73:26)
    at async Cli.run (/Users/<redacted>/.npm/_npx/<redacted>/node_modules/clipanion/lib/advanced/Cli.js:229:24)
    at async Cli.runExit (/Users/<redacted>/.npm/_npx/<redacted>/node_modules/clipanion/lib/advanced/Cli.js:238:28)
```
</details> 

### Steps To Reproduce

1. `npx create-bud-app --wordpress --customize`
2. npm
3. wordpress
4. swc
5. sass
6. (no libraries/frameworks)
7. eslint, prettier,stylelint 
1.HTML wrapper - no

### version

(preview release)

### Logs

```zsh
`$ npx create-bud-app --wordpress --customize --log`

Produces:
`Unknown Syntax Error: Unsupported option name ("--log").`
```

### Relevant .budfiles

```zsh
`$ npx create-bud-app --wordpress --customize --debug`

Produces:
`Unknown Syntax Error: Unsupported option name ("--debug").`
```

**Comment by bnjmnrsh** [comment]
The issue is due to this line of css in [index.css](https://github.com/roots/bud/blob/main/sources/create-bud-app/templates/vanilla/index.css.hbs) not validating:
    Line 19: `align-content: center;`

**Comment by kellymears** [comment]
I noticed this as well when I was checking out #2550. Thanks for creating the issue; I'll fix the boilerplate.
