### ISSUE TITLE
Build workflow fails with out of memory error

### ISSUE THREAD

**Issue by kellymears** [roots/bud#65]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Github build workflow fails with out of memory error

## Steps to reproduce

1. Submit a PR
2. Build fails

**Expected behavior:** 

Build succeeds if PR is buildable locally.

**Actual behavior:** 

Build fails. See https://github.com/roots/bud/runs/2647230668

**Reproduces how often:**

100%

## Versions

4.1.0

## Additional information

```sh
➤ YN0000: [@roots/bud-preset-recommend]: Process started
➤ YN0000: [@roots/bud-preset-recommend]: Internal Error: spawn ENOMEM
➤ YN0000: [@roots/bud-preset-recommend]:     at ChildProcess.spawn (internal/child_process.js:402:11)
➤ YN0000: [@roots/bud-preset-recommend]:     at Object.spawn (child_process.js:553:9)
➤ YN0000: [@roots/bud-preset-recommend]:     at Function.sR [as default] (/home/runner/work/bud/bud/.yarn/releases/yarn-sources.cjs:4:6917)
➤ YN0000: [@roots/bud-preset-recommend]:     at th.implementation (/home/runner/work/bud/bud/.yarn/releases/yarn-sources.cjs:249:1507)
➤ YN0000: [@roots/bud-preset-recommend]:     at th.exec (/home/runner/work/bud/bud/.yarn/releases/yarn-sources.cjs:252:1582)
➤ YN0000: [@roots/bud-preset-recommend]:     at th.run (/home/runner/work/bud/bud/.yarn/releases/yarn-sources.cjs:252:1753)
➤ YN0000: [@roots/bud-preset-recommend]:     at CCe (/home/runner/work/bud/bud/.yarn/releases/yarn-sources.cjs:256:5987)
➤ YN0000: [@roots/bud-preset-recommend]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
➤ YN0000: [@roots/bud-preset-recommend]:     at async s (/home/runner/work/bud/bud/.yarn/releases/yarn-sources.cjs:256:6086)
➤ YN0000: [@roots/bud-preset-recommend]:     at async mCe (/home/runner/work/bud/bud/.yarn/releases/yarn-sources.cjs:257:14)
➤ YN0000: [@roots/bud-preset-recommend]: Process exited (exit code 1), completed in 0s 774ms
➤ YN0000: The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
```

**Comment by kellymears** [comment]
@austinpray i have no idea what i can do to make this not the way it is

**Comment by kellymears** [comment]
Tried

- Setting `max-old-space-size` node env: 
```yml
- run: yarn build:ci
   env:
     NODE_OPTIONS: '--max-old-space-size=2048'
```

- Limiting yarn concurrency with the [`--jobs flag`](https://yarnpkg.com/cli/workspaces/foreach#options-j%2C-jobs%20%230)

**Comment by kellymears** [comment]
I set up caching for yarn berry and a bunch more jobs failed.

Then, inexplicably, this worked: https://github.com/roots/bud/actions/runs/871702891

**Comment by kellymears** [comment]
See #83

**Comment by kellymears** [comment]
We are using circleci until we can get of the bottom of this issue (ref #94)

**Comment by kellymears** [comment]
this is sorted by node update
