### ISSUE TITLE
Bug: [bud-postcss] JavaScript error / can't add PostCSS plugin

### ISSUE THREAD

**Issue by strarsis** [roots/bud#968]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Adding a PostCSS plugin doesn't work. A JavaScript error is logged during build.

#### What have you tried?
Following the bud postcss readme for adding a PostCSS plugin.

#### What insights have you gained?
Betas can still change and sometimes configuration has to be adjusted.

#### Possible solutions
Probably some bud configuration adjustments for the latest Sage 10 beta.

#### Temporary workarounds
Not really, PostCSS and PostCSS plugins are used and needed by the theme SCSS styles.

### Steps To Reproduce

1. `yarn add --dev @roots/bud-postcss`
2. `yarn add --dev postcss-inline-svg`
3. Add configuration to `bud.config.js` for a PostCSS workaround + adding the `PostCSS Inline SVG` plugin:
```js
/**
  * Add postcss-scss syntax
  *
  * @remarks
  * fix for @roots/bud@^5.0.0-next.16.
  * can be removed in @roots/bud@^5.0.0-next.17.
  *
  * @see {@link https://git.io/JM8ym}
  */
 .tap(bud => {
  const options = bud.build.items.postcss.options({});
  options.postcssOptions.syntax = 'postcss-scss';
})

// Add PostCSS inline SVG plugin
.tap(bud => {
  bud.postcss
    .setPlugin('postcss-inline-svg', require.resolve('postcss-inline-svg'))
});
````
4. Run the build `yarn build`. Notice the error about PostCSS during the initial stages of the build process. Also notice that the plugin is not used (the `svg-load` function by the `PostCSS Inline SVG` plugin is not interpolated).

### Expected Behavior

`PostCSS Inline SVG` plugin is being used and `svg-load` correctly interpolated and replaced with CSS by the plugin.

### Actual Behavior

`PostCSS Inline SVG` plugin not used, `svg-load` not interpolated. JavaScript error logged during the build process.

### Relevant Log Output

```shell
TypeError: Cannot read properties of undefined (reading 'getValues')
    at Item.options ([secure]/node_modules/@roots/bud-postcss/lib/cjs/postcss.extension.js:38:207)
    at Bud.<anonymous> ([secure]/bud.config.js:52:43)
    at Bud.tap ([secure]/node_modules/@roots/bud-framework/lib/cjs/Framework/methods/tap.js:31:8)
    at module.exports ([secure]/bud.config.js:51:3)
    at Configuration.<anonymous> ([secure]/node_modules/@roots/bud/lib/cjs/cli/Runner/config/dynamic.config.js:80:23)
    at Generator.next (<anonymous>)
    at [secure]/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter ([secure]/node_modules/tslib/tslib.js:113:16)
    at Configuration.invoke ([secure]/node_modules/@roots/bud/lib/cjs/cli/Runner/config/dynamic.config.js:70:38)
```

### Versions

- Remove `config` and `bootstrap` directories ([#2839](https://github.com/roots/sage/pull/2839))

**Comment by strarsis** [comment]
Edit: OK, this happens because instead of `app` an empty object as placeholder is passed to `options(...)`.
However, where is the `app` variable? When I try to pass it an error occurs that `app` is not defined:
````
ReferenceError: app is not defined
````

**Comment by strarsis** [comment]
My bad, the argument passed to the function in `bud.config.js` can be arbitrarily named and hence deviate from sample code.
In this case it was named `bud` instead of `app`, so I had to pass `bud` instead of `app`.
